server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称,修改hosts 添加127.0.0.1 eureka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心 只维护服务实例 不检索服务
    service-url:
      #设置与Eureka Server交互的地址 查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/ #如果超过（>2台）EurekaServer，用逗号隔开。集群指向其它eureka
#      defaultZone: http://eureka7001.com:7001/eureka/ #单机就是自己
#  server:
#    enable-self-preservation: false #关闭自我保护 服务不可用时及时踢除
#    eviction-interval-timer-in-ms: 2000